services:
  mensajeria-service:
    image:    sebasmo/mensajeria-service:latest
    container_name: mensajeria-service
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DB_USER=userdb
      - DB_PASS=passdb
      - JPA_DDL=create-drop
      - DB_HOST=jdbc:postgresql://db:5432/curso_springboot
    networks:
      - mynetwork

  serviceuser:
      image: andres727/serviceuser
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user
        SPRING_DATASOURCE_USERNAME: devdb
        SPRING_DATASOURCE_PASSWORD: a1b2c3d4
      networks:
        - backend


  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passdb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
